spring.application.name=pqrs

server.port=8080

# PostgreSQL (soporta variables de entorno con fallback a localhost)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pqrs_supermarket}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB